# Generated by Django 5.0.3 on 2024-05-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='')),
                ('shortName', models.CharField(max_length=255)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.categories')),
            ],
        ),
    ]
