# Generated by Django 5.0.3 on 2024-05-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_courses_createdat_courses_creator_courses_iscomplete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='href',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.courses'),
        ),
    ]
