# Generated by Django 5.0.3 on 2024-05-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_article_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='shortName',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='shortName',
            new_name='href',
        ),
    ]
