# Generated by Django 5.0.3 on 2024-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_courseuser_courses_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='shortName',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='shortName',
            new_name='href',
        ),
    ]
