# Generated by Django 5.0.3 on 2024-05-19 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_shortname_article_href_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='student_user', through='store.courseUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
