# Generated by Django 5.0.3 on 2024-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_courses_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
