# Generated by Django 5.0.3 on 2024-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_session_courseuser_cannot_register_twice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
