# Generated by Django 5.0.3 on 2024-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_comment_answer_alter_comment_isanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isAnswer',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='session',
        ),
    ]
