# Generated by Django 5.0.3 on 2024-06-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_comment_answer_alter_comment_isanswer_and_more'),
        ('store', '0017_notification'),
    ]

    operations = [
    ]
