# Generated by Django 5.0.3 on 2024-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
