# Generated by Django 5.0.3 on 2024-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_comment_article_alter_comment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='href',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='href',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
