# Generated by Django 5.0.3 on 2024-06-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subMenu', to='store.categories'),
        ),
    ]
