# Generated by Django 5.0.3 on 2024-06-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_session'),
        ('store', '0023_alter_courses_categoryid'),
    ]

    operations = [
    ]
