# Generated by Django 5.0.3 on 2024-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_ordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='support',
            field=models.CharField(default='telegram_group', max_length=255),
        ),
    ]
