# Generated by Django 5.0.3 on 2024-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_courses_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
