# Generated by Django 5.0.3 on 2024-07-03 14:50

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.dynamic_upload_to),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.dynamic_upload_to),
        ),
    ]
