# Generated by Django 5.0.3 on 2024-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_article_cover_alter_courses_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]),
        ),
    ]
