# Generated by Django 5.0.3 on 2024-07-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_comment_score'),
    ]

    operations = [
         migrations.RunSQL("""
            UPDATE core_user SET role = 'USER' WHERE is_staff = FALSE;
            UPDATE core_user SET role = 'ADMIN' WHERE is_staff = TRUE;
        """)
    ]
