# Generated by Django 5.0.3 on 2024-07-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mainCommentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.comment'),
        ),
    ]
