# Generated by Django 5.0.3 on 2024-07-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_courses_discount_alter_off_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.menus'),
        ),
    ]
