# Generated by Django 5.0.3 on 2024-07-11 22:23

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_menus_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=store.models.dynamic_upload_to),
        ),
    ]
