# Generated by Django 5.0.3 on 2024-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_menus_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='file',
            new_name='video',
        ),
    ]
