# Generated by Django 5.0.3 on 2024-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_rename_file_session_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='off',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
