# Generated by Django 5.0.3 on 2024-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_off_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
