# Generated by Django 5.0.3 on 2024-07-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_courseuser_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderModel',
        ),
    ]
