# Generated by Django 5.0.3 on 2024-07-18 15:52

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_courses_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='default/defImage.png', upload_to=store.models.dynamic_upload_to),
        ),
    ]
