# Generated by Django 5.0.3 on 2025-07-17 21:25

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_lesson_lessonvideo_topic_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='video_file',
            field=models.FileField(default='media/default/defImage.png', upload_to=store.models.uploadvideo),
        ),
    ]
