# Generated by Django 5.0.3 on 2025-07-18 17:25

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_lessonvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='video_file',
            field=models.FileField(default='default/', upload_to=store.models.uploadvideo),
        ),
    ]
