# Generated by Django 5.0.3 on 2024-05-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_created_at_user_name_user_role_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'USER'), ('A', 'ADMIN')], default='U', max_length=1),
        ),
    ]
