# Generated by Django 5.0.3 on 2024-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'USER'), ('A', 'ADMIN')], default='A', max_length=1),
        ),
    ]
