# Generated by Django 5.0.3 on 2024-05-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_User SET role = 'USER' WHERE role = 'U';",
            "UPDATE core_User SET role = 'ADMIN' WHERE role = 'A';",
        )
    ]
