# Generated by Django 5.0.3 on 2024-05-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240505_1419'),
    ]

    operations = [
       migrations.RunSQL( "delete from core_User where email is null or email='joerg@gmail.com' ",)
    ]
