# Generated by Django 5.0.3 on 2024-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order'),
        ('store', '0023_alter_courses_categoryid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='already ordered and registered'),
        ),
    ]
